title: Welcome to Marcus Munyiri Blog
author: Marcus Munyiri
email: marcusmunyiri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
#This Blog will review my Perfornal Profile|

# social links
twitter_username: https://www.instagram.com/m_m_munyiri/ # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
